import * as React from 'react'
import Layout from '../components/layout'
import Seo from '../components/seo'

const PrefacePage = () => {
  return (
    <Layout pageTitle="Preface">
      <h1>Vorwort</h1>
      <p>Werke von Komponistinnen finden heute immer häufiger Eingang in die Konzertprogramme. Dennoch ist die weibliche Seite im Kanon der Musikgeschichte wenig präsent. Gerade bei unbekannteren Komponistinnen gibt es in vielen Fällen nur spärliche oder ungenaue Informationen. Dies hat zur Folge, dass sich Interessierte selbst auf die Suche nach deren Lebensgeschichten machen müssen. Doch die Quellen sind begrenzt und es bedarf oft intensiver und zeitaufwändiger Recherche, um kleine Puzzleteile ausfindig zu machen. Daher ist die leichte Zugänglichkeit von Forschungsergebnissen – gerade was Komponistinnen angeht – ein wichtiger Schlüssel, um ihnen eine Stimme zu geben. Nur, wenn wir die bisher weniger beachtete weibliche Seite der Musikgeschichte in die bestehende Betrachtungsweise integrieren, kann ein vollständigeres, realitätsnahes Bild der Personen gezeichnet werden. 
        <br/>Doch wie kann man Komponistinnen die ihnen ohne Zweifel gebührende Geltung verschaffen, ihnen eine Stimme geben? Wie stellt man ihr Leben dar, um einen möglichst umfassenden Eindruck ihres Wirkens zu erhalten? Auch wenn die Kompositionen meist die aussagekräftigsten Zeugen des musikkulturellen Handelns einer Person sind, kann eine gleichzeitige Betrachtung von Leben und Werk das Verständnis wesentlich fördern. Im Falle einer unbekannten Komponistin ist daher eine Aufarbeitung ihrer Lebensgeschichte mithilfe der eruierten, prägnanten Daten, einer Netzwerkkontextualisierung sowie der Erörterung von gesellschaftlichen Einflüssen für die Musikwissenschaft ein relevanter Beitrag.
      </p>
      <p>Dokumente wie Taufbucheinträge oder Sterbeurkunden können ein Grundgerüst bilden. Briefe oder Zeitungsartikel verleihen einer Lebensgeschichte Farbe und Erwähnungen bringen Tiefe. So kann man sich auch aus wenigen Quellen ein Bild von einer Person, ihres Lebens und ihres Wirkens machen.
        <br/>Dokumentarbiografien wie die von Otto Erich Deutsch zu Schubert oder von Donald Burrows zu Händel haben diesen Ansatz verfolgt. Dabei ist das Ziel, Quellen so aufzubereiten, dass dieselben für sich stehen und so die Person selbst etwa durch ihre Briefe wieder gehört werden kann. Prägnanter Eine gezielte Anreicherung mit Hintergrundinformationen vervollständigt die Quellensammlung. Auf diese Weise können sich die Betrachtenden selbst ein Bild einer Person machen, ohne dass umfangreiche Vorkenntnisse oder Interpretationen der gewonnenen Daten notwendig sind.
        <br/>Dennoch ist wichtig zu bedenken, dass es das Idealbild einer objektiven Biografie nicht geben kann. Briefe sind immer für eine bestimmte Person geschrieben und bilden ab, wie etwas gesehen wurde. Auch Zeitungsartikel wie Rezensionen sind oft subjektive Meinungen mit einer kulturinteressierten Bevölkerung als Zielgruppe. Daher ist es für die Annäherung an eine Objektivität wichtig, die Quellen zusätzlich auf eine schlichte und möglichst neutrale Weise zu kontextualisieren. 
      </p>
      <p>Zusätzlich ist Musik kulturelles Handeln und somit sind bei der Auseinandersetzung mit Komponist:innen auch deren Netzwerke von zentraler Bedeutung. Diese können durch Erwähnungen in Quellen immer weiter erschlossen werden und bilden gleichzeitig neue Forschungsansatzpunkte. Durch die Bereitstellung von Informationen zu den genannten Personen, Werken und Orten werden die Verknüpfungen sicht- und greifbar. 
      </p>
      <p>Die vorliegende Arbeit beschäftigt sich mit der Berliner Komponistin, Pianistin, Sängerin und Musikpädagogin Jeannette Bürde, geb. Milder (1797–1875). <b>(Für Bürdes ausführliche Biografie siehe [Seite verlinken])</b>. Von Bürde sind bisher ausschließlich Lieder für Gesang mit Klavierbegleitung nachweisbar. Ihre Kompositionen zeichnen sich durch ein hohes Maß an Textausdeutung und eine reiche musikalische Bildersprache aus.
      <br/>Bürdes früheste Werke lassen sich auf 1824 datieren. In den darauffolgenden 25 Jahren veröffentlichte sie etwa alle fünf Jahre ein Liederheft mit je drei bis fünf vertonten Gedichten. Sie nutzte dafür hauptsächlich Texte von Heinrich Heine und Ludwig Uhland, aber auch Verse von Wilhelm Müller, Friedrich Schiller und Johann Wolfgang von Goethe. Aktuell lassen sich knapp 40 Kompositionen unter anderem durch Erwähnungen in Rezensionen und Briefen erschließen, davon sind 32 Lieder mit Noten im Erstdruck oder als Handschrift erhalten und zum Großteil in der digitalisierten Sammlung der Staatsbibliothek Berlin einsehbar. So ist ihre Musik die einfachste Möglichkeit, sich Bürde zu nähern. 
      </p>
      <p>Möchte man etwas über Bürdes Leben erfahren, wird es herausfordernder. Aktuell gibt es zu ihr nur sehr wenig Literatur. Fast alle heute existierenden Artikel zu Bürde basieren auf einem kurzen Eintrag in Carl von Ledeburs Tonkünstler-Lexicon Berlin’s (1861). Darüber hinaus gibt es kaum Informationen zu ihrem Leben und Wirken. Einige wenige Rückschlüsse lassen sich aus dem etwas besser aufgearbeiteten Lebensverlauf Anna Milders (Bürdes Schwester) ziehen; jedoch ist ein Großteil des Milder-Bürde-Nachlasses bisher unauffindbar. So stellen die erhaltenen Briefe und Dokumente die zentralen Zeugen ihrer Lebensgeschichte dar. Auf diesen Texten basierend war es mir 2023 möglich, für das Lexikon Musik und Gender im Internet (MUGI) einen Artikel zu Bürde zu veröffentlichen, welcher erstmals deutlich über Ledeburs Lexikoneintrag hinausgehend informiert. 
        <br/>Nun hat ein Lexikonartikel die Aufgabe, einen umfassenden Überblick zu einer Person zu geben, während eine Biografie detailliert den Lebensverlauf schildert. Letzteres ist aufgrund der spärlichen Informationslage und der großen Lücken aktuell nicht realisierbar. An dieser Stelle wird die Dokumentarbiografie interessant. Obschon es zu Bürdes Leben bei weitem nicht so viele Dokumente, Briefe und Rezensionen wie zu Schubert oder Händel gibt, können die wenigen Textzeugen Schlaglichter werfen und so eine Informationstiefe erzeugen, wie es einem Lexikonartikel nicht möglich ist. 
        <br/>Daher wurde für das Ziel, möglichst umfassend zu Bürdes Leben zu informieren, die Methode einer digitalen Dokumentenausgabe gewählt. So können Interessierte sich leicht zugänglich ein eigenes Bild von Bürde, ihrem Leben und ihrem Netzwerk machen. Zudem entsteht die Möglichkeit, dass Bürdes Stimme in der Musikgeschichte, der Musikpraxis und der musikwissenschaftlichen Forschung mehr Gehör findet. 
      </p>
      <p>Die Entscheidung, das Projekt digital umzusetzen, lag bei der Konzeption auf der Hand. Einfache Zugänglichkeit ist mit der wichtigste Faktor, um Informationen insbesondere zu Komponistinnen zu verbreiten. Eine öffentliche Website ist heutzutage deutlich leichter zugänglich als ein gedrucktes Buch, welches nur in ausgewählten Bibliotheken verfügbar ist oder käuflich erworben werden muss. 
        <br/>Hinzu kommen weitere Vorteile, welche eine digitale Edition gegenüber einer Druckausgabe bietet. Zunächst lassen sich neu gewonnene Erkenntnisse leicht einarbeiten und überholte Informationen korrigieren. Somit steht den Nutzenden stets die aktuellste Version zur Verfügung. Des Weiteren ist eine digitale Edition maschinenlesbar. Durch die standardisierte Codierung der Informationen können die Daten so auch in fachfremden Arbeiten (z.B. zu Kirchenbüchern im 19. Jahrhundert) einfach ausgelesen und weiterverwendet werden.
        <br/>Zuletzt ist eine zusätzliche Herausgabe einer gedruckten Version der Edition nachträglich zu einer digitalen Ausgabe deutlich leichter umsetzbar als andersherum.
        <br/>Die größten Herausforderungen dieses Projekts bildeten zunächst die Überlegungen zur Codierung und wie bereits vorhandene und standardisierte Umsetzungsformen digitaler Editionen an die Bedürfnisse der vorliegenden Textdokumente angepasst werden können. Hinzu kam, dass hinter vermeintlich kleinen Fragestellungen zeitintensive Recherchen stehen können, deren Ergebnis in der Edition lediglich in einem kurzen Satz Erwähnung findet. 
        <br/>Ein Beispiel für allgemeine Sachverhalte dieser Art ist die Suche nach dem Grab Bürdes. Hierfür wurde mehrfach der entsprechende Friedhof be- und durchsucht, sowie mit verschiedenen Berliner Ämtern Kontakt aufgenommen. All diese Recherchezeit mündete in dem schlichten Satz „Bürdes Grab ist nicht erhalten“. 
        <br/>Die Identifikation der genannten Personen birgt ähnliche Herausforderungen. Adressbücher und Ahnenforschungswebseiten können dabei zunächst eine große Hilfe sein. Dennoch kann es nicht selten vorkommen, dass sich die simple Recherche nach einem Geburts- oder Sterbedatum zu einem zeitintensiven Unterfangen ausweitet, an dessen Ende eine einfache Zahl steht. 
        <br/>Dennoch sind diese Recherchen und die gewonnenen Erkenntnisse ihre Mühe wert. Besonders wenn man bedenkt, dass die Forschungsergebnisse mithilfe der vorliegenden Website leicht zugänglich gemacht werden und so zukünftigen Interessierten die Recherche erleichtern. 
      </p>
      <p>Langfristig ist das Ziel, die vorliegende Website weiter mit Informationen rund um Bürde, ihr Leben und Œuvre sowie ihrem Netzwerk anzureichern. Eine Integration einer digitalen Edition ihrer Kompositionen inklusive Aufnahmen wird ebenfalls angestrebt. Näheres hierzu findet sich unter <b>Über das Projekt [Seite verlinken].</b>
      </p>
      <p>Sowohl die bereits vorliegende Edition als auch alle zukünftigen Erweiterungen sind ohne die Kooperation der Besitzenden der Quellen nicht denkbar. Zu danken ist daher allen Bibliotheken und Archiven, welche ihre Textdokumente zur Auswertung zur Verfügung stellen und es auch möglich machen, auf der vorliegenden Website die originalen Quellen einzusehen.
      </p>
      <p>Ein besonderer Dank geht an Nikolaus Gatter, den Vorsitzenden der Varnhagengesellschaft. Seit Beginn meiner Forschung zu Bürde (2022) stand er mir beratend zur Seite; er half sowohl bei kniffligen Transkriptionen, Identifikation von Personen und Fragen rund um die Berliner Salongesellschaft als auch bei der Kontextualisierung meiner gewonnenen Informationen. 
      </p>
      <p>Zuletzt möchte ich mich bei Julius Hauth bedanken, welcher die digitale Umsetzung dieses Projekts möglich gemacht hat. Sein Tool zur Darstellung von codierten Textdokumenten ermöglicht, dass Sie nun die vorliegende Website einsehen können. 
      </p>
      <p><i>Stuttgart, im Sommer 2025</i>
      <br/><i>Flora Völlger</i>
      </p>
    </Layout>
  )
}

export const Head = () => <Seo title="Preface" />

export default PrefacePage